version: '3'

services:
  hive:
    image: apache/hive:4.0.0-alpha-2
    container_name: hive7
    user: hive
    ports:
      - "10000:10000"  # HiveServer2
      - "10002:10002"  # HiveServer2 Web UI
      - "9083:9083"    # Metastore
    volumes:
      - ./Data/table:/dw2024
    environment:
      - SERVICE_NAME=hiveserver2
      - JAVA_HOME=/usr/local/openjdk-8
      - LANG=C.UTF-8
      - JAVA_VERSION=8u342
      - HADOOP_HOME=/opt/hadoop
      - HIVE_HOME=/opt/hive
      - TEZ_HOME=/opt/tez
    working_dir: /opt/hive
    entrypoint: sh -c "/entrypoint.sh"
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge
